site_name: BEAST.jl
repo_url: https://github.com/krcools/BEAST.jl
docs_dir: build
markdown_extensions:
    - mdx_math

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js
